---

base_locale: en
locales: [en]

ignore_unused:
  - "decidim.components.budget_category_voting.name"

ignore_missing:
  - decidim.participatory_processes.scopes.global
  - decidim.budgets.projects.budget_excess.close
  - decidim.budgets.projects.budget_excess.ok
  - decidim.budgets.projects.budget_summary.rules.title
