---

base_locale: en
locales: [en]

ignore_unused:
  - "decidim.components.budget_category_voting.name"

ignore_missing:
  - rule.*
  - projects_rule.*
  - minimum_projects_rule.*
  - projects_excess.*
  - vote_threshold_percent_rule.*
  - projects_rule_maximum_only.*
  - decidim.budgets.projects.budget_excess.close
  - decidim.budgets.projects.budget_excess.ok
  - decidim.budgets.projects.budget_summary.rules.title

